hrm/accounts/urls.py
from django.urls import path
from .views import HomeView, LoginView
from django.contrib.auth.views import LogoutView

app_name = 'accounts'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

hrm/hrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('scheduler/', include('scheduler.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrm/scheduler/urls.py
from django.urls import path
from .views import Apply, CandidateDetailView, HRDashboardView, InterviewerDashboardView, ScheduleDetailView, VerifyView, \
    ProfileView, SuccessApply, ScheduleDeleteView, TechnicalView, PracticalView, Search

app_name = 'scheduler'
urlpatterns = [
    path('apply/', Apply.as_view(), name='apply'),
    path('verify/<str:token>/', VerifyView.as_view(), name='verify'),
    path('success_apply/<str:token>/', SuccessApply.as_view(), name='success_apply'),
    path('profile/<str:token>/', ProfileView.as_view(), name='profile'),
    path('hr_dashboard/', HRDashboardView.as_view(), name='hr_dashboard'),
    path('candidate_detail/<int:pk>/', CandidateDetailView.as_view(), name='candidate_detail'),
    path('interviewer_dashboard/', InterviewerDashboardView.as_view(), name='interviewer_dashboard'),
    path('schedule_detail/<int:pk>/', ScheduleDetailView.as_view(), name='schedule_detail'),
    path('technical_view/<int:pk>/', TechnicalView.as_view(), name='technical_view'),
    path('practical_view/<int:pk>/', PracticalView.as_view(), name='practical_view'),
    path('schedule_delete/<int:pk>/<int:candidate_id>/', ScheduleDeleteView.as_view(), name='schedule_delete'),
    path('search/', Search.as_view(), name='search'),
]

hrm/accounts/models.py
from django.db import models
from django.shortcuts import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django_fsm import FSMField, transition

# Create your models here.


class Vacancies(models.Model):
    post = models.CharField(max_length=50)
    technologies = models.CharField(max_length=50)
    experience = models.CharField(max_length=50)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return '{} {}'.format(self.post, self.technologies)


class Candidate(models.Model):
    SHORTLIST = 'shortlist'
    TECHNICAL = 'technical'
    PRACTICAL = 'practical'
    HR = 'hr'
    REJECTED = 'rejected'
    SELECTED = 'selected'
    STATUS_TAG = [
        (SHORTLIST, 'Short Listed'),
        (TECHNICAL, 'For Technical Round'),
        (PRACTICAL, 'For Practical Round'),
        (HR, 'For HR Round'),
        (REJECTED, 'Rejected'),
        (SELECTED, 'Selected'),
    ]
    EXPERIENCE_CHOICE = [
        ('2', '0 - 1'),
        ('1 - 2', '1 - 2'),
        ('2 - 3', '2 - 3'),
        ('3 - Above', '3 - Above'),
    ]
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    birth_date = models.DateField()
    mobile = PhoneNumberField()
    email = models.EmailField(unique=True)
    token = models.CharField(max_length=30, null=True, blank=True)
    resume = models.FileField(upload_to='resumes/', null=True, blank=True)
    applied_for = models.ForeignKey(Vacancies, on_delete=models.CASCADE)
    status = FSMField(default=SHORTLIST, choices=STATUS_TAG)
    experience = models.CharField(default='0 - 1', choices=EXPERIENCE_CHOICE, max_length=20)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        return reverse('scheduler:candidate_detail', args=[self.pk])

    @transition(field='status', source=SHORTLIST, target=TECHNICAL)
    def technical_round(self):
        pass

    @transition(field='status', source=TECHNICAL, target=PRACTICAL)
    def practical_round(self):
        pass

    @transition(field='status', source=PRACTICAL, target=HR)
    def hr_round(self):
        pass

    @transition(field='status', source=HR, target=SELECTED)
    def select(self):
        pass

    @transition(field='status', source=[SHORTLIST, TECHNICAL, PRACTICAL, HR], target=REJECTED)
    def reject(self):
        pass


class Address(models.Model):
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    landmark = models.CharField(max_length=100)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='address')

    def __str__(self):
        return '{} - {}'.format(self.state, self.city)


class Questions(models.Model):
    question = models.CharField(max_length=50)

    def __str__(self):
        return self.question

hrm/scheduler/models.py
from django.db import models
from accounts.models import Candidate, Questions
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.


class Schedule(models.Model):
    NOT_SPECIFY = 'not_specify'
    SELECTED = 'selected'
    REJECTED = 'rejected'
    STATUS_TAG = [
        (NOT_SPECIFY, 'Not Specify'),
        (SELECTED, 'Selected'),
        (REJECTED, 'Rejected'),
    ]
    TECHNICAL = 'technical'
    PRACTICAL = 'practical'
    HR = 'hr'
    INTERVIEW_TYPE = [
        (TECHNICAL, 'Technical Round'),
        (PRACTICAL, 'Practical Round'),
        (HR, 'HR Round'),
    ]

    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='candidate_schedule')
    hr = models.ForeignKey(User, on_delete=models.CASCADE, related_name='hr')
    interviewer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='interviewer')
    schedule_time = models.DateTimeField()
    interview_type = models.CharField(max_length=50, choices=INTERVIEW_TYPE)
    comment = models.TextField(blank=True, null=True)
    status = models.CharField(default=NOT_SPECIFY, choices=STATUS_TAG, max_length=50)

    def __str__(self):
        return '{} - {}'.format(self.candidate, self.status)

    def get_absolute_url(self):
        return reverse('scheduler:schedule_detail', args=[self.pk])


class Evaluation(models.Model):
    NOT_SPECIFIED = 'not_specified'
    UNSATISFACTORY = 'unsatisfactory'
    SATISFACTORY = 'satisfactory'
    AVERAGE = 'average'
    ABOVE_AVERAGE = 'above_average'
    EXCEPTIONAL = 'exceptional'
    QUESTION_TAG = [
        (NOT_SPECIFIED, 'Not Specified'),
        (UNSATISFACTORY, 'Unsatisfactory'),
        (SATISFACTORY, 'satisfactory'),
        (AVERAGE, 'Average'),
        (ABOVE_AVERAGE, 'Above Average'),
        (EXCEPTIONAL, 'Exceptional'),
    ]
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    question_tag = models.CharField(default=NOT_SPECIFIED, choices=QUESTION_TAG, max_length=50)

    def __str__(self):
        return '{} - {}'.format(self.question, self.question_tag)

hrm/scheduler/views.py
import json
from django.core.serializers import serialize
from builtins import super
from django.utils import timezone
from django.shortcuts import render, reverse, HttpResponseRedirect, redirect
from django.urls import reverse_lazy
from accounts.models import Candidate, Address, Questions
from django.views.generic import TemplateView, DetailView, ListView, FormView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import ScheduleForm, ApplyForm, AddressForm, EvaluationForm, EvaluationCommentForm
from .models import Schedule, Evaluation
from django.utils.crypto import get_random_string
from django.forms import modelformset_factory, formset_factory
from extra_views import FormSetView
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail
from django.views.decorators.clickjacking import xframe_options_exempt
from django.utils.decorators import method_decorator

# Create your views here.


class Apply(FormView):
    form_class = ApplyForm
    template_name = 'scheduler/apply.html'
    success_url = None

    def form_valid(self, form):
        token = get_random_string(length=8)
        instance = form.save(commit=False)
        instance.token = token
        instance.save()
        self.success_url = reverse('scheduler:success_apply', args=[token])
        msg = 'http://127.0.0.1:8000/scheduler/verify/' + str(token)
        email = 'nikunjjoshi04@gmail.com'
        send_mail("Apply Test", msg, settings.EMAIL_HOST_USER, [email], fail_silently=False)
        return super(Apply, self).form_valid(form=form)


class SuccessApply(TemplateView):
    template_name = 'scheduler/success_apply.html'

    def get_context_data(self, **kwargs):
        context = super(SuccessApply, self).get_context_data(**kwargs)
        context['candidate'] = Candidate.objects.get(token=self.kwargs.get('token', None))
        return context


class VerifyView(FormView):
    form_class = AddressForm
    template_name = 'scheduler/verify.html'

    def form_valid(self, form):
        experience = form.cleaned_data['experience']
        candidate = Candidate.objects.get(token=self.kwargs.get('token', None))
        resume = self.request.FILES['file']
        candidate.resume = resume
        candidate.experience = experience
        candidate.save()
        form.instance.candidate = candidate
        form.save()
        return super(VerifyView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(VerifyView, self).get_context_data(**kwargs)
        context['candidate'] = Candidate.objects.get(token=self.kwargs.get('token', None))
        return context

    def get_success_url(self):
        return reverse('scheduler:profile', args=[self.kwargs.get('token', None)])


@method_decorator(xframe_options_exempt, name='get')
class ProfileView(TemplateView):
    template_name = 'scheduler/candidate_profile.html'

    def get_context_data(self, **kwargs):
        kwargs = super(ProfileView, self).get_context_data()
        kwargs['candidate'] = Candidate.objects.get(token=self.kwargs.get('token', None))
        return kwargs


class List(PermissionRequiredMixin, ListView):
    permission_required = None
    login_url = 'accounts:login'
    permission_denied_message = 'Not Allow...!!!'
    model = None
    template_name = None


class Detail(PermissionRequiredMixin, DetailView):
    permission_required = None
    login_url = 'accounts:login'
    permission_denied_message = 'Not Allow...!!!'
    model = None
    template_name = None


class HRDashboardView(TemplateView):
    permission_required = ['accounts.view_candidate']
    login_url = 'accounts:login'
    permission_denied_message = 'Not Allow...!!!'
    model = Candidate
    template_name = 'scheduler/hr_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(HRDashboardView, self).get_context_data()
        context['candidates'] = Candidate.objects.all()
        context['schedules'] = Schedule.objects.select_related('candidate').all()
        return context


class CandidateDetailView(Detail, FormView):
    permission_required = [
        'accounts.view_candidate',
        'accounts.change_candidate',
    ]
    login_url = 'accounts:login'
    permission_denied_message = 'Not Allow...!!!'
    model = Candidate
    template_name = 'scheduler/candidate_detail.html'
    form_class = ScheduleForm

    def form_valid(self, form):
        interview_type = form.cleaned_data['interview_type']
        candidate = Candidate.objects.get(id=self.kwargs.get('pk', None))
        if interview_type == Candidate.TECHNICAL:
            candidate.technical_round()
        elif interview_type == Candidate.PRACTICAL:
            candidate.practical_round()
        elif interview_type == Candidate.HR:
            candidate.hr_round()
        else:
            candidate.status = Candidate.SHORTLIST
        candidate.save()
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CandidateDetailView, self).get_form_kwargs()
        kwargs['pk'] = self.kwargs.get('pk', None)
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('scheduler:candidate_detail', args=[self.kwargs.get('pk', None)])

    def get_context_data(self, **kwargs):
        context = super(CandidateDetailView, self).get_context_data(**kwargs)
        context['hrs'] = User.objects.filter(is_staff=True, is_superuser=False)
        context['interviewer'] = User.objects.filter(is_staff=False, is_superuser=False)
        return context


class InterviewerDashboardView(PermissionRequiredMixin, ListView):
    permission_required = [
        'scheduler.change_schedule',
        'scheduler.view_schedule'
    ]
    login_url = 'accounts:login'
    permission_denied_message = 'Not Allow...!!!'
    model = Schedule
    template_name = 'scheduler/interviewer_dashboard.html'


class ScheduleDetailView(View):
    def get(self, request, pk):
        schedule = Schedule.objects.get(id=self.kwargs.get('pk', None))
        if schedule.interview_type == Schedule.TECHNICAL:
            print(schedule.interview_type)
            return redirect(reverse('scheduler:technical_view', args=[self.kwargs.get('pk', None)]))
        else:
            print(schedule.interview_type)
            return redirect(reverse('scheduler:practical_view', args=[self.kwargs.get('pk', None)]))


class PracticalView(Detail, FormView):
    permission_required = [
        'scheduler.change_schedule',
        'scheduler.view_schedule'
    ]
    login_url = 'accounts:login'
    permission_denied_message = 'Not Allow...!!!'
    model = Schedule
    template_name = 'scheduler/practical_schedule_detail.html'
    form_class = EvaluationCommentForm

    def form_valid(self, form):
        comment = form.cleaned_data['comment']
        status = form.cleaned_data['status']
        schedule = Schedule.objects.get(id=self.kwargs.get('pk', None))
        schedule.comment = comment
        schedule.status = status
        if status == Schedule.REJECTED:
            schedule.candidate.status = Candidate.REJECTED
            schedule.candidate.save()
        if schedule.interview_type == Schedule.HR and status == Schedule.SELECTED:
            schedule.candidate.select()
            schedule.candidate.save()
        schedule.save()
        return super(PracticalView, self).form_valid(form)

    def get_success_url(self):
        return reverse('scheduler:schedule_detail', args=[self.kwargs.get('pk', None)])


class TechnicalView(FormSetView):
    template_name = 'scheduler/technical_schedule_detail.html'
    form_class = EvaluationForm
    # initial = [{'question': 'QUE1'}, {'question': 'QUE2'}]
    factory_kwargs = {'extra': 0, 'max_num': None,
                      'can_order': False, 'can_delete': False}
    comment_form = EvaluationCommentForm

    def formset_valid(self, formset):
        schedule = Schedule.objects.get(id=self.kwargs.get('pk', None))
        for each in formset:
            question = each.cleaned_data.get('question', None)
            question_tag = each.cleaned_data.get('question_tag', None)
            questions_obj = Questions.objects.get(question=question)
            Evaluation.objects.create(
                question=questions_obj,
                schedule=schedule,
                question_tag=question_tag
            )
        form_comment = self.comment_form(self.request.POST)
        if form_comment.is_valid():
            comment = form_comment.cleaned_data.get('comment', None)
            status = form_comment.cleaned_data.get('status', None)
            schedule.comment = comment
            schedule.status = status
            if status == Schedule.REJECTED:
                schedule.candidate.status = Candidate.REJECTED
                schedule.candidate.save()
            schedule.save()
        return super(TechnicalView, self).formset_valid(formset)

    def get_success_url(self):
        return reverse('scheduler:schedule_detail', args=[self.kwargs.get('pk', None)])

    def formset_invalid(self, formset):
        print(formset)
        return super(TechnicalView, self).formset_invalid(formset)

    def get_initial(self):
        initial = []
        for each in Questions.objects.all():
            initial.append({'question': each.question})
        return initial

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk', None)
        context = super(TechnicalView, self).get_context_data(**kwargs)
        try:
            context['schedule'] = Schedule.objects.get(id=pk)
        except Exception as e:
            context['schedule'] = None
            print('Error Is :- ', e, type(e))
        context['comment_form'] = self.comment_form
        return context

hrm/templates/scheduler/candidate_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Candidate Detail</title>
{% endblock %}
{% block content %}
<div class="breadcrumb mb-4">
    <li class="breadcrumb-item pt-1 text-center"><a href="{% url 'scheduler:hr_dashboard' %}">Dashboard</a></li>
    <li class="breadcrumb-item pt-1 text-center">Candidate Profile</li>
</div>

<div class="container">
    <div class="row my-2">
        <div class="col-lg-8 order-lg-2">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#schedule" data-toggle="tab" class="nav-link">Create Schedule</a>
                </li>
            </ul>
            <div class="tab-content py-4">
                <div class="tab-pane active" id="profile">
                    <h2 class="mb-4">Candidate Info</h2>
                    <div class="row bg-light pt-3 pb-0 my-3">
                        <div class="col-md-6">
                            <h5 class="mb-3">{{ candidate.first_name.capitalize }}
                                <small>{{ candidate.last_name.capitalize }}
                                </small>
                            </h5>
                        </div>
                        <div class="col-md-6">
                            <h5 class="mb-3">{{ candidate.get_status_display }}</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h5>Applied For :-</h5>
                            <p class="ml-5"> {{ candidate.applied_for.post.capitalize }}</p>
                            <hr>
                            <h5>Contact :-</h5>
                            <div class="ml-5">
                                <p><i class="fa fa-mobile" aria-hidden="true"></i> {{ candidate.mobile }}</p>
                                <p><i class="fa fa-envelope-o" aria-hidden="true"></i> {{ candidate.email }}</p>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <h5> Experience :- </h5>
                            <p class="ml-5"> {{ candidate.experience }} </p>
                            <hr>
                            <h5 class="mb-0"> Address :- </h5>
                            <div class="ml-5">
                                <p> {{ candidate.address.first.city.capitalize }} <small>
                                    ({{ candidate.address.first.state.capitalize }})</small></p>
                                <p> {{ candidate.address.first.street.capitalize }} </p>
                                <p> {{ candidate.address.first.landmark }} - 360470</p>
                            </div>
                        </div>
                    </div>
                    <!--/row-->
                </div>
                <div class="tab-pane" id="schedule">
                    <h2 class="mb-4">Create Schedule</h2>
                    <div class="container py-2 px-2">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="form-group">
                                {% if form.interview_type.errors %}
                                <ol>
                                    {% for error in form.interview_type.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                                {% endif %}
                                <div class="row">
                                    <div class="col-md-4">
                                        <h4>{{ form.interview_type.label_tag }}</h4>
                                    </div>
                                    <div class="col-md-8">
                                        {{ form.interview_type }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {% if form.interviewer.errors %}
                                <ol>
                                    {% for error in form.interviewer.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                                {% endif %}
                                <div class="row">
                                    <div class="col-md-4">
                                        <h4>{{ form.interviewer.label_tag }}</h4>
                                    </div>
                                    <div class="col-md-8">
                                        {{ form.interviewer }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {% if form.schedule_time.errors %}
                                <ol>
                                    {% for error in form.schedule_time.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                                {% endif %}
                                <div class="row">
                                    <div class="col-md-4">
                                        <h4>{{ form.schedule_time.label_tag }}</h4>
                                    </div>
                                    <div class="col-md-8">
                                        {{ form.schedule_time }}
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-block btn-success" type="submit">Make Schedule</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 order-lg-1 text-center">
            <img src="//placehold.it/150" class="mx-auto img-fluid img-circle d-block" alt="avatar">
            <h5 class="mt-2">Upload a different photo</h5>
            <label class="custom-file disabled">
                <input type="file" id="file" class="custom-file-input">
                <span class="custom-file-control">Choose file</span>
            </label>
        </div>
    </div>
    <table class="table mb-5">
        <thead class="thead-light">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Schedules For</th>
            <th>Interviewer</th>
            <th>Time</th>
            <th>Status</th>
            <th>Info</th>
        </tr>
        </thead>
        <tbody>
        {% for each in candidate.candidate_schedule.all %}
        <tr>
            <td>{{ each.id }}</td>
            <td>
                {{ each.candidate.first_name }}
                <small>{{ each.candidate.last_name }}</small>
            </td>
            <td>{{ each.get_interview_type_display }}</td>
            <td>
                {{ each.interviewer.first_name.capitalize }}
                <small>{{ each.interviewer.last_name.capitalize }}</small>
            </td>
            <td>
                {{ each.schedule_time|date:'d-m-Y' }}
                <br>
                {{ each.schedule_time|time:'TIME_FORMAT' }}
            </td>
            <td>{{ each.get_status_display }}</td>
            <td>
                <div class="row">
                    <div class="col-md-6">
                        <a href="{{ each.get_absolute_url }}">Details</a>
                    </div>
                    <div class="col-md-6">
                        <a href="{% url 'scheduler:schedule_delete' each.id candidate.id %}">Delete</a>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block js %}
<script>

</script>
<script type="text/javascript">
    $(function () {
        $("#id_schedule_time").datetimepicker({
        format: 'YYYY-MM-DD HH:mm',
        minDate: moment()
    });
    });


</script>

<script>
    $(document).ready(function(){
        $('#id_interviewer').html(
            '<option value="" selected="">---------</option>{% for each in interviewer %}<option value="{{ each.id }}">{{ each.get_full_name }}</option>{% endfor %}'
        )
        $('#id_interview_type').change(function (){
            var interview_type =  $(this).val();
            if (interview_type == 'hr')
            {
             $('#id_interviewer').html(
                '<option value="" selected="">---------</option>{% for each in hrs %}<option value="{{ each.id }}">{{ each.get_full_name }}</option>{% endfor %}'
             )
            }
            else
            {
             $('#id_interviewer').html(
                '<option value="" selected="">---------</option>{% for each in interviewer %}<option value="{{ each.id }}">{{ each.get_full_name }}</option>{% endfor %}'
             )
            }
        });
    });


</script>
{% endblock %}

hrm/templates/scheduler/practical_schedule_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Candidate Detail</title>
{% endblock %}
{% block content %}
<div class="breadcrumb mb-4">
    {% if user.is_staff %}
    <li class="breadcrumb-item pt-1 text-center"><a href="{% url 'scheduler:hr_dashboard' %}">Dashboard</a></li>
    {% else %}
    <li class="breadcrumb-item pt-1 text-center"><a href="{% url 'scheduler:interviewer_dashboard' %}">Dashboard</a></li>
    {% endif %}
    <li class="breadcrumb-item pt-1 text-center">Interview</li>
</div>

<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Profile</a>
        </li>
        <li class="nav-item">
            <a href="" data-target="#resume" data-toggle="tab" class="nav-link">Resume</a>
        </li>
    </ul>
    <div class="tab-content py-4">
        <div class="tab-pane active" id="profile">
            <h2 class="mb-4">Candidate Info</h2>
            <div class="row bg-light pt-3 pb-0 my-3">
                <div class="col-md-6">
                    <h5 class="mb-3">{{ schedule.candidate.first_name.capitalize }}
                        <small>{{ schedule.candidate.last_name.capitalize }}
                        </small>
                    </h5>
                </div>
                <div class="col-md-6">
                    <h5 class="mb-3">{{ schedule.candidate.get_status_display }}</h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h5>Applied For :-</h5>
                    <p class="ml-5"> {{ schedule.candidate.applied_for.post.capitalize }}</p>
                    <hr>
                    <h5>Contact :-</h5>
                    <div class="ml-5">
                        <p><i class="fa fa-mobile" aria-hidden="true"></i> {{ schedule.candidate.mobile }}</p>
                        <p><i class="fa fa-envelope-o" aria-hidden="true"></i> {{ schedule.candidate.email }}</p>
                    </div>
                    <h5>Interviewer :-</h5>
                    <div class="ml-5">
                        <p><i class="fa fa-user-o" aria-hidden="true"></i>
                            {{ schedule.interviewer.get_full_name.capitalize}}
                        </p>
                    </div>
                </div>

                <div class="col-md-6">
                    <h5> Experience :- </h5>
                    <p class="ml-5"> {{ schedule.candidate.experience }} </p>
                    <hr>
                    <h5 class="mb-0"> Address :- </h5>
                    <div class="ml-5">
                        <p> {{ schedule.candidate.address.first.city.capitalize }} <small>
                            ({{ schedule.candidate.address.first.state.capitalize }})</small></p>
                        <p> {{ schedule.candidate.address.first.street.capitalize }} </p>
                        <p> {{ schedule.candidate.address.first.landmark }} - 360470</p>
                    </div>
                </div>
            </div>
            <!--/row-->
        </div>
        <div class="tab-pane" id="resume">
            <h2 class="mb-4">Resume</h2>
            <img src="{{ schedule.candidate.resume.url }}">
            <iframe src="{{ schedule.candidate.resume.url }}" height="600" width="100%"></iframe>

        </div>
    </div>
</div>
<hr>

{% if schedule.comment == None and user == schedule.interviewer %}
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {% if form.comment.errors %}
        <ol>
            {% for error in form.comment.errors %}
            <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
        {% endif %}
        <label class="small mb-1" for="{{ form.comment.id_for_label }}">
            {{ form.comment.label_tag }}</label>
        {{ form.comment }}
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            {% if form.status.errors %}
            <ol>
                {% for error in form.status.errors %}
                <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ol>
            {% endif %}
            <label class="small mb-1" for="{{ form.comment.id_for_label }}">
                {{ form.status.label_tag }}</label>
            {{ form.status }}
        </div>
        <div class="form-group col-md-6">
            <label class="small mb-2" for="btn">
                Submit</label>
            <button id="btn" class="btn btn-block btn-success mt-1" type="submit">Submit</button>
        </div>
    </div>
</form>
{% else %}
<h2>Comment From Interviewer</h2>
<p class="my-2 mx-5">{{ schedule.comment }}</p>
<hr>
<h2>Interview Status</h2>
<p class="my-2 mx-5">{{ schedule.status }}</p>
{% endif %}

{% endblock %}

{% block js %}
<script type="text/javascript">
    $(function () {
        $("#id_schedule_time").datetimepicker({
        format: 'YYYY-MM-DD HH:mm',
        minDate: moment()
    });
    });


</script>
{% endblock %}